# Generated by Django 6.0 on 2025-12-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='movie_posters/')),
                ('plot_summary', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('rating_average', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('availability_status', models.CharField(choices=[('COMING_SOON', 'Coming Soon'), ('NOW_SHOWING', 'Now Showing'), ('ENDED', 'Ended')], default='COMING_SOON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movies.genre')),
            ],
            options={
                'ordering': ['-release_date', 'title'],
            },
        ),
    ]
