# Generated by Django 6.0 on 2026-01-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mpa_rating',
            field=models.CharField(blank=True, choices=[('G', 'G (General Audiences)'), ('PG', 'PG (Parental Guidance Suggested)'), ('PG-13', 'PG-13 (Parents Strongly Cautioned)'), ('R', 'R (Restricted)'), ('NC-17', 'NC-17 (Adults Only)')], help_text='MPA rating (e.g., G, PG, PG-13, R, NC-17)', max_length=6, null=True),
        ),
    ]
