# Generated by Django 6.0 on 2025-12-27 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('on_sale', 'On Sale'), ('canceled', 'Canceled'), ('ended', 'Ended')], default='planned', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='theaters.screen')),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['screen', 'start_time'], name='showtimes_s_screen__5ed6b1_idx'), models.Index(fields=['movie', 'start_time'], name='showtimes_s_movie_i_274781_idx')],
                'constraints': [models.UniqueConstraint(fields=('screen', 'start_time'), name='uniq_screen_start_time')],
            },
        ),
    ]
