# Generated by Django 6.0 on 2026-01-05 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_user_movie_review',
        ),
    ]
